{% set name = "xcube-cds" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xcube-dev/xcube-cds/archive/v{{ version }}.tar.gz
  sha256: 340aeb11facce81f5dd0dbf766ec8f8ec2e97916ec7ba72d3c2916bf05c7b56e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    # Python
    - python >={{ python_min }}
    # Required
    - cdsapi >=0.7.2
    - jsonschema >=3.2.0
    - numpy >=1.17
    - pandas
    - python-dateutil >=2.8.1
    - xarray >=0.18.2
    - xcube >=0.9.0
test:
  requires:
    - python {{ python_min }}
  imports:
    - xcube_cds

about:
  summary: xcube plugin for the Climate Data Store (CDS) API
  home: https://github.com/xcube-dev/xcube-cds
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube-cds is an xcube plugin which can generate data cubes from the Copernicus Climate Data Store (CDS) API.
  doc_url: https://github.com/xcube-dev/xcube-cds/blob/master/README.md
  dev_url: https://github.com/xcube-dev/xcube-cds

extra:
  recipe-maintainers:
    - AliceBalfanz
    - b-yogesh
    - forman
    - konstntokas
    - pont-us
    - ruchimotwaniBC
    - TejasMorbagal
    - thomasstorm
    - TonioF
